# syntax=docker/dockerfile:1
#Which "official Java image" ?
FROM maven:3.8.3-openjdk-17-slim AS build
# Set the working directory to /app
WORKDIR /app

# Copy the pom.xml files for both modules
COPY pom.xml .
COPY kafka-producer-wikimedia/pom.xml ./kafka-producer-wikimedia/
COPY kafka-consumer-database/pom.xml ./kafka-consumer-database/

# Install the dependencies for both modules
RUN mvn -B dependency:go-offline

# Copy the source code for both modules
COPY kafka-producer-wikimedia/src ./kafka-producer-wikimedia/src
COPY kafka-consumer-database/src ./kafka-consumer-database/src

# Run the application using the spring-boot:run goal
CMD mvn -pl kafka-producer-wikimedia,kafka-consumer-database spring-boot:run





